-- AlterTable
ALTER TABLE "WebOrder" ADD COLUMN "subtotalAmount" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "WebOrder" ADD COLUMN "discountAmount" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "WebOrder" ADD COLUMN "deliveryFee" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "WebOrder" ADD COLUMN "couponCode" TEXT;
