import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import LayoutFromComponents from '@/components/layout/Layout';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit", // Esto crea la variable CSS --font-outfit
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'], // Especifica los pesos que usarás
  display: 'swap', // Mejora la carga de la fuente
});

export const metadata: Metadata = {
  title: "CRM APP",
  description: "Generated by Emi Cabanillas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased bg-background text-foreground`}>
        <LayoutFromComponents>
          {children}
        </LayoutFromComponents>
      </body>
    </html>
  );
}
