import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import LayoutFromComponents from '@/components/layout/Layout';
import { Toaster } from "react-hot-toast";

const outfit = Outfit({
  variable: "--font-outfit", // Esto crea la variable CSS --font-outfit
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'], // Especifica los pesos que usarás
  display: 'swap', // Mejora la carga de la fuente
});

export const metadata: Metadata = {
  title: "IGNITE CRM - Toma el control de tu negocio",
  keywords: [
    "CRM",
    "gestión de clientes",
    "automatización de ventas",
    "gestión de relaciones con clientes",
    "software CRM",
    "gestión de contactos",
    "seguimiento de ventas",
    "análisis de clientes",
    "mejora de relaciones con clientes",
  ],
  authors: [
    {
      name: "Emi Cabanillas",
    }],
  creator: "Emi Cabanillas",
  description: "Generated by Emi Cabanillas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${outfit.variable} antialiased bg-background text-foreground`}
      >
        <Toaster
          position="top-right" // Posición de las notificaciones
          toastOptions={{
            // Estilos para los toasts
            style: {
              background: "var(--color-muted)", // Usando tus variables de color
              color: "var(--color-foreground)",
              border: "1px solid var(--color-border)",
            },
            // Estilos específicos para éxito y error
            success: {
              iconTheme: {
                primary: "var(--color-success)",
                secondary: "var(--color-success-foreground)",
              },
            },
            error: {
              iconTheme: {
                primary: "var(--color-destructive)",
                secondary: "var(--color-destructive-foreground)",
              },
            },
          }}
        />
        <LayoutFromComponents>{children}</LayoutFromComponents>
      </body>
    </html>
  );
}
